import React, { createContext, useContext, useState } from 'react'

const LanguageContext = createContext()

export function useLanguage() {
  return useContext(LanguageContext)
}

const T = {
  nl: {
    nav: {
      home: 'Home',
      alphaess: 'Over AlphaESS',
      warmtefonds: 'Warmtefonds',
      aanbod: 'Aanbod',
      hoeWerktHet: 'Hoe werkt het?',
      waaromVoltrax: 'Waarom Voltrax',
      faq: 'FAQ',
      cta: 'Bereken besparing',
    },
    home: {
      badge: 'De #1 thuisbatterij van Nederland',
      hero1: 'Sla uw zonnestroom op.',
      hero2: 'Gebruik hem slim.',
      heroDesc: 'Met de AlphaESS SMILE G3 benut u tot 92% van uw eigen zonnestroom. Het Energy Management System regelt alles automatisch.',
      calcBtn: 'Bereken mijn besparing',
      howBtn: 'Hoe werkt het?',
      stat1: 'Max. zelfverbruik',
      stat2: 'Installaties',
      stat3: 'Garantie',
      productBadge: 'AlphaESS SMILE G3',
      productSub: '9,3 tot 111,3 kWh capaciteit',
      featuresBadge: 'AlphaESS SMILE G3',
      featuresTitle: 'Bouw mee aan een groene toekomst',
      featuresDesc: 'De AlphaESS thuisbatterij is meer dan opslag. Het is een slim energiesysteem dat automatisch optimaliseert voor maximum rendement en minimum kosten.',
      features: [
        { title: 'Maximaal zelfverbruik', desc: 'Sla uw overschot zonnestroom op en gebruik hem precies wanneer u het nodig heeft. Van 35% naar meer dan 80% eigen stroom.' },
        { title: 'Verdien met de energiemarkt', desc: 'Het EMS koopt automatisch bij negatieve of lage tarieven, en levert terug op piekuren. Volledig automatisch, dag en nacht.' },
        { title: 'Energieonafhankelijk', desc: 'Bereid u voor op elke situatie. Essentiële apparaten blijven werken, ook bij stroomstoringen. Zorgeloos en duurzaam.' },
        { title: 'Bewezen rendement', desc: 'Meer dan 200.000 geïnstalleerde systemen wereldwijd. Marktleider in thuisenergieopslag met 10 jaar fabrieksgarantie.' },
      ],
      productTitle: 'Thuisbatterij voor elk huis in Nederland',
      productDesc: 'Modulair uitbreidbaar van 9,3 tot 111,3 kWh, gebouwd met LFP-technologie voor maximale veiligheid en levensduur. Stil, IP55-gecertificeerd en compatibel met alle grote omvormers.',
      productBullets: [
        'LFP-technologie, meer dan 10.000 laadcycli',
        'Modulair: van 9,3 tot 111,3 kWh',
        'IP55 voor binnen en buiten installatie',
        'Smart EMS met realtime monitoring via app',
        'Compatibel met alle grote omvormers',
      ],
      viewOffer: 'Bekijk aanbod',
      calcSavings: 'Bereken mijn besparing',
      specCapacity: 'Capaciteit',
      specTech: 'Technologie',
      specCycles: 'Laadcycli',
      specWarranty: 'Garantie',
      testimonialsTitle: 'Echte verhalen van tevreden klanten',
      testimonialsSub: 'Meer dan 200.000 huishoudens wereldwijd gingen u voor.',
      testimonials: [
        { name: 'Bart', text: 'Batterij doet wat hij moet doen. Zonder haperen. Integratie met het platform verliep heel vlot en geeft mij duidelijk inzicht. Zo ben ik zeker dat de batterij nuttig werk levert zonder dat ik er naar hoef te kijken.', stars: 5 },
        { name: 'Marina van den Eynde', text: 'De batterij werkt zeer goed. De app is gemakkelijk te gebruiken en zeer duidelijk. Je weet direct hoeveel percent er nog in de batterij aanwezig is, hoeveel watt je zonnepanelen opbrengen en hoeveel je van het net moet nemen.', stars: 5 },
        { name: 'Luc', text: 'We waren aangenaam verrast door de prijs. De vertegenwoordiger gaf een goede uitleg over de werking en beantwoordde geduldig al onze vragen. Alle werken zijn stipt uitgevoerd.', stars: 5 },
        { name: 'Marc De Schinckel', text: 'De AlphaESS batterij geeft een mooi rendement. We hebben nu twee batterijen die ons voorzien van de nodige reserve-elektriciteit. Via de app kan je perfect productie en verbruik opvolgen.', stars: 5 },
      ],
      whyBadge: 'Waarom VOLTRAX',
      whyTitle: 'Niet zomaar een batterijinstallateur',
      whySub: 'Wij leveren meer dan hardware. Gecertificeerd, all-in en zonder verborgen kosten.',
      whyMore: 'Alles over Voltrax',
      whyUsps: [
        { title: 'Officieel AlphaESS dealer', desc: 'Directe fabriekssupport, originele onderdelen en de volledige 10 jaar fabrieksgarantie, zoals beloofd.' },
        { title: 'Eigen gecertificeerde monteurs', desc: 'Geen onderaannemers. Onze eigen monteurs installeren uw systeem vakkundig. Gemiddeld een halve dag.' },
        { title: '0% rente via Warmtefonds', desc: 'Officieel Warmtefonds partner. Tot € 8.500 lenen, wij verzorgen de volledige aanvraag voor u.' },
        { title: 'All-in offerte, niks extra', desc: 'Batterij, omvormer, installatie, BTW en garantie, alles inbegrepen. Geen verrassingen achteraf.' },
        { title: 'AlphaCloud altijd gratis', desc: 'Geen abonnement, geen licentiekosten. Monitoring, updates en EMS voor altijd inbegrepen.' },
        { title: 'Levenslange service & monitoring', desc: 'Na installatie blijven wij bereikbaar. Wij activeren de app en staan klaar jaar na jaar.' },
      ],
      installTitle: 'Professionele installatie',
      installDesc: 'Van advies tot oplevering door onze gecertificeerde monteurs. Geen verborgen kosten.',
      ctaBadge: 'Kosteloos, geen registratie',
      ctaTitle: 'Ontdek wat een batterij voor u betekent',
      ctaDesc: 'Vul uw verbruik in en zie in 2 minuten uw persoonlijke besparing en terugverdientijd.',
      ctaBtn: 'Start de berekening',
      ctaSub: '100% vrijblijvend',
      footerDealer: 'Officieel AlphaESS dealer Nederland',
      footerWarranty: '10 jaar garantie',
    },
    calc: {
      back: 'Terug',
      stepOf: (s, total) => `Stap ${s} van ${total}`,
      steps: ['Zonneproductie', 'Jaarverbruik', 'Teruglevering', 'Tarieven', 'Capaciteit', 'Investering'],
      prev: 'Vorige',
      next: 'Volgende',
      viewReport: 'Bekijk mijn rapport',
      calculating: 'Berekenen...',
      enterToContinue: 'Druk op Enter om door te gaan',
      error: 'Er is een fout opgetreden bij het berekenen. Probeer het opnieuw.',
      step1Title: 'Hoeveel zonnestroom wekt u op?',
      step1Sub: 'Kijk op uw omvormer of energierekening voor uw jaarproductie.',
      step1Label: 'Jaarlijkse zonneproductie',
      step1Tooltip: 'Totale jaarlijkse opbrengst van uw zonnepanelen in kilowattuur.',
      step1Hint: 'Een gemiddeld huishouden met 12 panelen produceert circa 3.600 tot 4.800 kWh per jaar.',
      step2Title: 'Wat is uw jaarlijks energieverbruik?',
      step2Sub: 'Te vinden op uw jaarafrekening of via uw slimme meter.',
      step2Label: 'Jaarlijks elektriciteitsverbruik',
      step2Tooltip: 'Het totale jaarlijkse stroomverbruik van uw woning.',
      step2Hint: 'Een gemiddeld Nederlands huishouden verbruikt 3.000 tot 4.500 kWh per jaar. Met een elektrische auto of warmtepomp kan dit oplopen tot 7.000 kWh of meer.',
      step3Title: 'Hoeveel levert u terug aan het net?',
      step3Sub: 'Uw teruglevering is de zonnestroom die u niet zelf verbruikt.',
      step3Label: 'Jaarlijkse teruglevering',
      step3Tooltip: 'Het aantal kWh dat u per jaar teruglevert aan het energienet.',
      step3Hint: 'Gemiddeld leveren huishoudens met zonnepanelen 40 tot 60% van hun productie terug. Bij 4.500 kWh productie is dat circa 1.800 tot 2.700 kWh.',
      step4Title: 'Wat zijn uw energietarieven?',
      step4Sub: 'Vind deze tarieven op uw energiecontract of rekening.',
      step4LabelDynamic: 'Heeft u een dynamisch energiecontract?',
      step4DynamicNo: 'Nee, vast tarief',
      step4DynamicYes: 'Ja, dynamisch (EPEX)',
      step4DynamicHint: 'Uw batterij profiteert maximaal van uurprijzen op de energiemarkt.',
      step4LabelInkoop: 'Inkoopprijs elektriciteit',
      step4TooltipInkoop: 'Het tarief dat u betaalt voor stroom die u van het net afneemt.',
      step4LabelTerug: 'Teruglevertarief',
      step4TooltipTerug: 'Het tarief dat u ontvangt voor stroom die u teruglevert aan het net.',
      step4LabelVergoeding: 'Terugleververgoeding',
      step4TooltipVergoeding: 'Extra vergoeding van uw leverancier voor teruglevering, boven het teruglevertarief.',
      step4LabelKosten: 'Terugleverkosten',
      step4TooltipKosten: 'Kosten die uw leverancier in rekening brengt voor teruglevering.',
      perKwh: 'per kWh',
      perJaar: 'per jaar',
      step5Title: 'Kies uw batterijcapaciteit',
      step5Sub: 'Selecteer de capaciteit die het beste bij uw situatie past. Grotere capaciteit geeft meer rendement.',
      batteries: [
        { kWh: 9.3,  label: '9,3 kWh',  desc: 'Ideaal voor 1-2 personen met beperkt verbruik' },
        { kWh: 18.6, label: '18,6 kWh', desc: 'Populaire keuze voor een gemiddeld gezin' },
        { kWh: 27.9, label: '27,9 kWh', desc: 'Optimaal voor hoog verbruik of laadpaal' },
        { kWh: 37.2, label: '37,2 kWh', desc: 'Maximale onafhankelijkheid voor grotere gezinnen' },
        { kWh: 46.5, label: '46,5 kWh', desc: 'Hoge capaciteit voor energieintensieve huishoudens' },
        { kWh: 111.3, label: '111,3 kWh', desc: 'Maximale capaciteit, volledig energieonafhankelijk' },
      ],
      recommended: 'Aanbevolen voor uw profiel',
      batteryUpgradeHint: (tv, recLabel) => `Op basis van uw ${tv.toLocaleString('nl-NL')} kWh teruglevering past een ${recLabel} beter bij uw profiel — hogere opbrengst, snellere terugverdientijd.`,
      step6Title: 'Wat is uw investeringsbedrag?',
      step6Sub: 'Inclusief batterij, installatie en BTW, zoals op de offerte.',
      step6Label: 'Totale investering',
      step6Tooltip: 'De totale kosten inclusief batterij, installatie en BTW.',
      warmtefondsTitle: 'Warmtefonds partner',
      warmtefondsDesc: 'Via VOLTRAX kunt u tot 8.500 euro lenen via het Nationaal Warmtefonds, mogelijk met 0% rente. Wij regelen dit voor u.',
    },
    results: {
      adjust: 'Aanpassen',
      downloadPdf: 'Download PDF',
      loadingPdf: 'Laden\u2026',
      loading: 'Rapport laden\u2026',
      annualBenefitLabel: 'Geschat jaarlijks voordeel',
      perYear: 'per jaar, energiebesparing + marktoptimalisatie',
      perMonth: 'Per maand',
      payback: 'Terugverdientijd',
      netAfter10: 'Netto na 10 jaar',
      currentSituation: 'Huidige situatie',
      withoutBattery: 'Zonder batterij',
      withAlpha: 'Met AlphaESS',
      withBattery: 'Met batterij',
      solarProduction: 'Zonne-opwek',
      solarSub: 'uw panelen per jaar',
      directSelfUse: 'Direct zelfverbruik',
      exportedToGrid: 'Teruggeleverd aan net',
      exportedSub: 'ongebruikt overschot',
      gridImport: 'Inkoop van net',
      gridImportSub: 'betaalt u vol tarief',
      feedinCosts: 'Terugleverkosten',
      feedinSub: 'vaste vergoeding aan uw leverancier',
      solarEqualSub: 'Gelijk aan de huidige situatie',
      baSelfConsumpSubL: 'Aandeel van opgewekte zonne-energie dat direct in de woning wordt gebruikt',
      baSelfConsumpSubR: 'Verhoogd door opslag en geoptimaliseerd gebruik van zonne-energie',
      baSelfDirectSubFull: 'Aandeel van uw totale verbruik dat direct door zonne-energie wordt gedekt',
      baTerugSubL: 'Overschot aan zonne-energie wordt teruggeleverd aan het elektriciteitsnet',
      baTerugSubR: 'Overschot wordt opgeslagen in de batterij en later in huis gebruikt',
      baNetInjectie: 'Resterende netinjectie',
      baNetInjectieSub: (gross, stored, net) => `Van ${gross} kWh overschot: ${stored} kWh opgeslagen, ${net} kWh nog naar net`,
      baNetDepSubL: 'Mate waarin uw energiebehoefte wordt gedekt door eigen opwek',
      baNetDepSubR: 'Sterk verhoogd door gebruik van opgeslagen en lokaal opgewekte energie',
      baGridImportSubL: 'Aankoop van elektriciteit van het net wanneer opwek onvoldoende is',
      baGridImportSubR: 'Sterk verminderd door inzet van opgeslagen zonne-energie',
      baMarktOpt: 'Slimme marktoptimalisatie',
      baMarktSubL: 'Niet actief in de huidige situatie',
      baMarktSubR: 'Energie wordt geladen bij lage uurprijzen en ingezet of teruggeleverd bij hoge marktprijzen',
      baBatStorage: 'Zelf gebruikt i.p.v. teruggeleverd',
      baBatStorageSub: 'Overschot aan zonne-energie wordt opgeslagen en zelf gebruikt in plaats van teruggeleverd aan het net',
      baFeedinSubL: 'Niet van toepassing in de huidige situatie',
      baFeedinSubR: 'Niet van toepassing binnen dynamisch aangestuurd energiesysteem',
      baFeedinActiveSubL: 'Wat u nu betaalt aan terugleverkosten over uw teruglevering',
      baFeedinActiveSubR: 'Minder teruglevering door opslag → lagere terugleverkosten',
      totalSelfUse: 'Totaal zelfverbruik',
      stillExported: 'Nog teruggeleverd',
      lessToGrid: (n) => `${n} kWh minder naar net`,
      gridImportWithSub: (n) => `${n} kWh minder dan nu`,
      energySaving: 'Energiebesparing',
      energySavingSub: (tk) => `minder inkopen${tk > 0 ? ' + geen terugleverkosten' : ''}`,
      smartOptTitle: 'Slimme marktoptimalisatie',
      smartOptDesc: 'Uw batterij laadt op wanneer stroom goedkoop is en levert op dure piekuren. Zo profiteert u automatisch van dagelijkse prijsverschillen op de energiemarkt.',
      viaEpex: 'via EPEX SPOT koppeling',
      financialOverview: 'Financieel overzicht',
      investment: 'Investering',
      annualBenefit: 'Jaarlijks voordeel',
      paybackPeriod: 'Terugverdientijd',
      netAfter10Label: 'Netto na 10 jaar',
      inclInstall: (kWh) => `${kWh} kWh incl. installatie`,
      year: 'jaar',
      viewCalc: 'Bekijk volledige berekening',
      gridAvoided: 'Netafname vermeden',
      lessExportRevenue: 'Minder exportopbrengst',
      missedExportTotal: 'Gemiste terugleververgoeding',
      feedinSaved: 'Terugleverkosten bespaard',
      feedinMissed: 'Terugleververgoeding gemist',
      emsArbitrage: 'EMS arbitrage (direct)',
      subtotalEnergy: 'Subtotaal energiestroom',
      emsDayPeak: 'EMS dag-piek optimalisatie',
      totalAnnual: 'Totaal jaarlijks voordeel',
      calcDisclaimer: 'Stap 1–2 zijn gebaseerd op uw invoer en actuele EPEX-marktdata. Stap 3 gaat uit van het CBS historisch gemiddelde (~5%/jr, 2010–2024). Stap 4 volgt het wettelijke afbouwpad van saldering 2027–2031. Werkelijke resultaten kunnen afwijken.',
      emsExplainer: 'Uw AlphaESS EMS handelt automatisch op de energiemarkt. Het systeem laadt op bij lage EPEX-prijzen en levert op piekuren. Dit is de grootste waardedrijver van uw systeem — volledig automatisch, dag en nacht.',
      warmtefondsLabel: 'Nationaal Warmtefonds',
      warmtefondsTitle: 'Financiering via VOLTRAX, 0% rente mogelijk',
      warmtefondsDesc: 'Tot \u20ac 8.500 lenen via het Nationaal Warmtefonds. Bij inkomen onder \u20ac 60.000 betaalt u 0% rente. Wij regelen alles.',
      warmteTags: ['Tot \u20ac 8.500', '0% rente mogelijk', 'Wij regelen alles'],
      ctaTitle: 'Klaar voor persoonlijk advies?',
      ctaDesc: 'Op basis van dit rapport stellen onze specialisten een offerte op maat samen. Volledig vrijblijvend.',
      ctaBtn: 'Vraag gratis advies aan',
      disclaimer: 'Indicatieve berekening op basis van uw verbruiksdata en marktgemiddelden. Werkelijke resultaten kunnen afwijken.',
      recalculate: 'Andere getallen invoeren',
      personalReport: 'Persoonlijk energierapport',
      maximaalVoordeel: 'Maximaal voordeel',
      perDayLabel: 'Per dag',
      howItWorksTitle: 'Zo werkt uw AlphaESS',
      howStep1Title: 'Batterij leert uw patroon',
      howStep1Desc: 'De eerste 4 weken analyseert het systeem uw verbruik en bouwt op naar maximale efficiëntie.',
      howStep2Title: '35\u201390% voor zonnestroom',
      howStep2Desc: "Dit deel van de capaciteit slaat uw eigen zonnestroom op en levert 's avonds wanneer de panelen stoppen.",
      howStep3Title: 'Rest speelt de energiemarkt',
      howStep3Desc: 'De resterende buffer laadt automatisch bij lage EPEX-prijzen en ontlaadt op piekuren. Dag en nacht, volledig automatisch.',
      waitingTitle: 'Wat u nu verliest zonder batterij',
      waitingMissedSavings: 'Gemiste besparing',
      waitingExtraCosts: 'Extra netkosten',
      waitingFeedin: 'Terugleverkosten',
      waitingTotal: 'Totaal gemist per jaar',
      waitingPerMonth: (n) => `Elke maand wachten kost u \u20ac${n} aan gemiste besparing.`,
      waitingBanner: (low, high) => `Elke maand zonder batterij laat u naar schatting \u20ac${low}\u2013\u20ac${high} aan waarde liggen.`,
      calcExplainGridAvoided: (kwh, pE) => `U vermeed ${kwh} kWh netinkoop \u00d7 \u20ac${pE}/kWh. Zonnestroom opgeslagen overdag, gebruikt 's avonds.`,
      calcExplainExportLoss: (kwh, pT) => `${kwh} kWh blijft nu in huis in plaats van terugleveren voor \u20ac${pT}/kWh. Dit is de eerlijke aftrekpost.`,
      calcExplainArbitrage: (kwh, pE, pT) => `${kwh} kWh \u00d7 (\u20ac${pE} \u2212 \u20ac${pT}) \u00d7 22% rendementsmarge.`,
      calcExplainEms: (totalCycles, solarCycles, bat, spreadLow, spreadHigh, emsLow, emsHigh) =>
        `Uw batterij maakt ${totalCycles} laad/ontlaad cycli per jaar. ${solarCycles} komen van zonnestroom, de rest zijn pure EPEX-cycli: laden voor \u20ac${spreadLow}/kWh, ontladen voor \u20ac${spreadHigh}/kWh. ${totalCycles} cycli \u00d7 ${bat} kWh \u00d7 \u20ac${spreadLow}\u2013\u20ac${spreadHigh} = \u20ac${emsLow}\u2013\u20ac${emsHigh}/jaar.`,
      dynamicContractLabel: 'Heeft u een dynamisch energiecontract?',
      dynamicNo: 'Nee, vast tarief',
      dynamicYes: 'Ja, dynamisch (EPEX)',
      dynamicHint: 'Uw batterij profiteert maximaal van uurprijzen op de energiemarkt.',
      perJaarShort: 'per jaar',
      valueBreakdownTitle: 'Zo verdient u terug',
      valueBreakdownBullets: [
        'Meer eigen zonnestroom gebruiken',
        'Minder stroom inkopen van het net',
        'Minder terugleveren tegen lage vergoeding',
        'Slim laden en ontladen op dynamische prijzen',
      ],
      v1Lbl: 'Minder netinkoop',
      v1Sub: 'Uw eigen zonnestroom \u2019s avonds en \u2019s nachts benut, niet weggegeven aan het net',
      v2Lbl: 'Terugleverkosten vermeden',
      v2Sub: 'Geen extra terugleverheffing meer aan uw energieleverancier',
      v3Lbl: 'Slimme batterijsturing',
      v3Sub: 'Automatisch laden bij lage stroomprijs, ontladen bij hoge prijs',
      openDetails: 'Hoe is dit berekend?',
      step1Basis: 'Minder stroom inkopen',
      step1BasisSub: 'U verbruikt uw eigen zonnestroom — elke kWh die u niet inkoopt scheelt direct geld',
      step2Epex: 'Slim laden en ontladen',
      step2EpexSub: 'Automatisch laden bij lage EPEX-tarieven, ontladen op dure piektijden — dag en nacht, volledig automatisch',
      step3Uplift: 'Stroom wordt elk jaar duurder',
      step3UpliftSub: 'Gebaseerd op CBS-energieprijsontwikkeling ~5%/jr · uw besparing groeit automatisch mee',
      step4Bonus: 'Saldering verdwijnt 2027–2031',
      step4BonusSub: 'U levert dan bijna niets meer terug — uw batterij vangt dat op',
      infoNotBaseline: 'Informatieve prognose — niet in basislijn',
      totalBenefitLabel: 'Totaal geschat jaarvoordeel',
      smartTitle: 'Slimme optimalisatie met AlphaESS',
      smartSubTrigger: 'Klik voor uitleg: hoe laadt en ontlaadt de batterij slim?',
      smartP1: 'Uw AlphaESS-batterij monitort continu de actuele stroomprijs. Het systeem beslist zelfstandig wanneer laden voordelig is en wanneer u energie kunt terugleveren of intern gebruiken.',
      smartBullet1: 'Laadt automatisch op bij lage of negatieve EPEX-prijzen',
      smartBullet2: 'Ontlaadt op dure piekuren, u betaalt dan niks aan het net',
      smartBullet3: 'Volledig automatisch, dag en nacht, geen actie vereist',
      smartRangeLbl: 'Extra waarde via slimme sturing',
      netResultTitle: 'Netto resultaat na 10 jaar',
      netResultSub: (price) => `Na terugverdienen van uw investering van \u20ac${price} houdt u dit over`,
      baTitle: 'Uw situatie: voor en na de batterij',
      baCurrentTag: 'Huidig',
      baNewTag: 'Met batterij',
      baWithTitle: 'Met AlphaESS batterij',
      baSelfConsump: 'Zelfverbruik',
      baSelfConsumpSub: 'van eigen zonnestroom benut',
      baSelfConsumpBasis: '% van uw zonnestroom',
      baGridImport: 'Netstroom inkoop',
      baExport: 'Zelf gebruikt van opwek',
      baExportSubBefore: 'direct van uw zonnepanelen',
      baExportSubAfter: 'via zonnepanelen + batterij',
      baNetCosts: 'Jaarlijkse netkosten',
      baNetCostsSub: 'incl. terugleverkosten',
      baNetEarning: 'Netto stroomopbrengst',
      baNetEarningSub: 'uw exportopbrengst overtreft uw netinkoop',
      baAnnualSaving: 'Jaarlijkse besparing',
      baCurrentDynamic: 'Huidig dynamisch contract',
      baCurrentFixed: 'Huidig vast contract',
      baCurrentDynamicHint: 'Met batterij stapt u over naar dynamisch \u2014 maximaal rendement',
      baNewDynamic: 'Dynamisch geoptimaliseerd + batterij',
      baNewFixed: 'Dynamisch contract + batterij',
      baSolarOutput: 'Totale zonneopbrengst',
      baSolarOutputSub: 'Uw jaarlijkse opwek via zonnepanelen',
      baSelfDirect: 'Direct zelfverbruik',
      baSelfDirectSub: 'van uw jaarverbruik gedekt door zon',
      baTeruglevering: 'Teruglevering aan net',
      baTerugleveringSub: (pT, pE) => `u ontvangt \u20ac\u2009${pT}/kWh \u2014 maar koopt terug voor \u20ac\u2009${pE}/kWh`,
      baNetDep: 'Zelfvoorzienendheid',
      baNetDepSub: '% van uw verbruik gedekt door eigen bronnen',
      baMissedValue: 'Slimme marktoptimalisatie',
      baMissedValueSub: 'zonder batterij geen automatische piekprijsoptimalisatie',
      baBatCaptures: 'Batterij vangt op',
      baBatCapturesSub: 'zonnoverschot benut i.p.v. teruglevering naar net',
      baSelfUsedNotExported: (n) => `${n} kWh zelf verbruikt i.p.v. teruggeleverd`,
      baGridImportBatterySub: (n) => `${n} kWh minder ingekocht door verbruik uit batterij`,
      baEpexRow: 'EPEX dynamisch contract',
      baEpexRowSub: 'laden bij lage uurprijs, ontladen op piektijden',
    },
  },

  en: {
    nav: {
      home: 'Home',
      alphaess: 'About AlphaESS',
      warmtefonds: 'Heat Fund',
      aanbod: 'Products',
      hoeWerktHet: 'How it works',
      waaromVoltrax: 'Why Voltrax',
      faq: 'FAQ',
      cta: 'Calculate savings',
    },
    home: {
      badge: 'The #1 home battery in the Netherlands',
      hero1: 'Store your solar energy.',
      hero2: 'Use it smart.',
      heroDesc: 'With the AlphaESS SMILE G3 you use up to 92% of your own solar power. The Energy Management System handles everything automatically.',
      calcBtn: 'Calculate my savings',
      howBtn: 'How does it work?',
      stat1: 'Max. self-consumption',
      stat2: 'Installations',
      stat3: 'Warranty',
      productBadge: 'AlphaESS SMILE G3',
      productSub: '9.3 to 111.3 kWh capacity',
      featuresBadge: 'AlphaESS SMILE G3',
      featuresTitle: 'Build towards a greener future',
      featuresDesc: 'The AlphaESS home battery is more than storage. It is a smart energy system that automatically optimises for maximum yield and minimum costs.',
      features: [
        { title: 'Maximum self-consumption', desc: 'Store your surplus solar power and use it exactly when you need it. From 35% to over 80% own power.' },
        { title: 'Earn from the energy market', desc: 'The EMS automatically buys at negative or low rates, and feeds back at peak hours. Fully automatic, day and night.' },
        { title: 'Energy independent', desc: 'Be prepared for any situation. Essential devices keep running, even during power outages. Worry-free and sustainable.' },
        { title: 'Proven returns', desc: 'Over 200,000 installed systems worldwide. Market leader in home energy storage with a 10-year factory warranty.' },
      ],
      productTitle: 'Home battery for every house in the Netherlands',
      productDesc: 'Modularly expandable from 9.3 to 111.3 kWh, built with LFP technology for maximum safety and longevity. Silent, IP55-certified and compatible with all major inverters.',
      productBullets: [
        'LFP technology, more than 10,000 charge cycles',
        'Modular: from 9.3 to 111.3 kWh',
        'IP55 for indoor and outdoor installation',
        'Smart EMS with real-time monitoring via app',
        'Compatible with all major inverters',
      ],
      viewOffer: 'View products',
      calcSavings: 'Calculate my savings',
      specCapacity: 'Capacity',
      specTech: 'Technology',
      specCycles: 'Charge cycles',
      specWarranty: 'Warranty',
      testimonialsTitle: 'Real stories from satisfied customers',
      testimonialsSub: 'More than 200,000 households worldwide have gone before you.',
      testimonials: [
        { name: 'Bart', text: "The battery does what it should. Without a hitch. Integration with the platform went very smoothly and gives me clear insight. I'm sure the battery is doing useful work without me having to watch it.", stars: 5 },
        { name: 'Marina van den Eynde', text: 'The battery works very well. The app is easy to use and very clear. You immediately know the battery percentage, how many watts your panels are producing and how much you need from the grid.', stars: 5 },
        { name: 'Luc', text: 'We were pleasantly surprised by the price. The representative gave a clear explanation and patiently answered all our questions. All work was carried out on time.', stars: 5 },
        { name: 'Marc De Schinckel', text: 'The AlphaESS battery gives a great return. We now have two batteries providing our reserve electricity. Via the app you can perfectly monitor production and consumption.', stars: 5 },
      ],
      whyBadge: 'Why VOLTRAX',
      whyTitle: 'Not just another battery installer',
      whySub: 'We deliver more than hardware. Certified, all-in and without hidden costs.',
      whyMore: 'Everything about Voltrax',
      whyUsps: [
        { title: 'Official AlphaESS dealer', desc: 'Direct factory support, original parts and the full 10-year factory warranty, as promised.' },
        { title: 'Our own certified technicians', desc: 'No subcontractors. Our own technicians install your system expertly. Average half a day.' },
        { title: '0% interest via Heat Fund', desc: 'Official Warmtefonds partner. Borrow up to €8,500. We handle the entire application for you.' },
        { title: 'All-in quote, nothing extra', desc: 'Battery, inverter, installation, VAT and warranty, all included. No surprises afterwards.' },
        { title: 'AlphaCloud always free', desc: 'No subscription, no licence fees. Monitoring, updates and EMS included forever.' },
        { title: 'Lifetime service & monitoring', desc: 'After installation we stay reachable. We activate the app and are there year after year.' },
      ],
      installTitle: 'Professional installation',
      installDesc: 'From advice to completion by our certified technicians. No hidden costs.',
      ctaBadge: 'Free, no registration',
      ctaTitle: 'Discover what a battery means for you',
      ctaDesc: 'Enter your usage and see your personal savings and payback period in 2 minutes.',
      ctaBtn: 'Start the calculation',
      ctaSub: '100% no obligation',
      footerDealer: 'Official AlphaESS dealer Netherlands',
      footerWarranty: '10-year warranty',
    },
    calc: {
      back: 'Back',
      stepOf: (s, total) => `Step ${s} of ${total}`,
      steps: ['Solar production', 'Annual usage', 'Grid export', 'Tariffs', 'Capacity', 'Investment'],
      prev: 'Previous',
      next: 'Next',
      viewReport: 'View my report',
      calculating: 'Calculating...',
      enterToContinue: 'Press Enter to continue',
      error: 'An error occurred during calculation. Please try again.',
      step1Title: 'How much solar power do you generate?',
      step1Sub: 'Check your inverter or energy bill for your annual production.',
      step1Label: 'Annual solar production',
      step1Tooltip: 'Total annual output of your solar panels in kilowatt-hours.',
      step1Hint: 'An average household with 12 panels produces approximately 3,600 to 4,800 kWh per year.',
      step2Title: 'What is your annual energy consumption?',
      step2Sub: 'Found on your annual statement or via your smart meter.',
      step2Label: 'Annual electricity consumption',
      step2Tooltip: 'The total annual electricity consumption of your home.',
      step2Hint: 'An average Dutch household consumes 3,000 to 4,500 kWh per year. With an electric car or heat pump this can rise to 7,000 kWh or more.',
      step3Title: 'How much do you feed back to the grid?',
      step3Sub: "Your grid export is the solar power you don't consume yourself.",
      step3Label: 'Annual grid export',
      step3Tooltip: 'The number of kWh you feed back to the energy grid per year.',
      step3Hint: 'On average, households with solar panels feed back 40 to 60% of their production. For 4,500 kWh that is approximately 1,800 to 2,700 kWh.',
      step4Title: 'What are your energy tariffs?',
      step4Sub: 'Find these on your energy contract or bill.',
      step4LabelDynamic: 'Do you have a dynamic energy contract?',
      step4DynamicNo: 'No, fixed tariff',
      step4DynamicYes: 'Yes, dynamic (EPEX)',
      step4DynamicHint: 'Your battery benefits fully from hourly price differences on the energy market.',
      step4LabelInkoop: 'Electricity purchase price',
      step4TooltipInkoop: 'The rate you pay for electricity drawn from the grid.',
      step4LabelTerug: 'Feed-in tariff',
      step4TooltipTerug: 'The rate you receive for electricity fed back to the grid.',
      step4LabelVergoeding: 'Feed-in bonus',
      step4TooltipVergoeding: 'Additional compensation from your supplier for feeding back, above the feed-in tariff.',
      step4LabelKosten: 'Feed-in costs',
      step4TooltipKosten: 'Costs your supplier charges for feeding back to the grid.',
      perKwh: 'per kWh',
      perJaar: 'per year',
      step5Title: 'Choose your battery capacity',
      step5Sub: 'Select the capacity that best suits your situation. Larger capacity gives higher returns.',
      batteries: [
        { kWh: 9.3,  label: '9.3 kWh',  desc: 'Ideal for 1-2 people with limited consumption' },
        { kWh: 18.6, label: '18.6 kWh', desc: 'Popular choice for an average family' },
        { kWh: 27.9, label: '27.9 kWh', desc: 'Optimal for high consumption or EV charger' },
        { kWh: 37.2, label: '37.2 kWh', desc: 'Maximum independence for larger families' },
        { kWh: 46.5, label: '46.5 kWh', desc: 'High capacity for energy-intensive households' },
        { kWh: 111.3, label: '111.3 kWh', desc: 'Maximum capacity, fully energy independent' },
      ],
      recommended: 'Recommended for your profile',
      batteryUpgradeHint: (tv, recLabel) => `Based on your ${tv.toLocaleString('en-NL')} kWh export, a ${recLabel} battery suits your profile better — higher yield, faster payback.`,
      step6Title: 'What is your investment amount?',
      step6Sub: 'Including battery, installation and VAT, as on the quote.',
      step6Label: 'Total investment',
      step6Tooltip: 'Total costs including battery, installation and VAT.',
      warmtefondsTitle: 'Heat Fund partner',
      warmtefondsDesc: 'Via VOLTRAX you can borrow up to \u20ac8,500 through the National Heat Fund, possibly at 0% interest. We arrange everything for you.',
    },
    results: {
      adjust: 'Adjust',
      downloadPdf: 'Download PDF',
      loadingPdf: 'Loading\u2026',
      loading: 'Loading report\u2026',
      annualBenefitLabel: 'Estimated annual benefit',
      perYear: 'per year, energy savings + market optimisation',
      perMonth: 'Per month',
      payback: 'Payback period',
      netAfter10: 'Net after 10 yrs',
      currentSituation: 'Current situation',
      withoutBattery: 'Without battery',
      withAlpha: 'With AlphaESS',
      withBattery: 'With battery',
      solarProduction: 'Solar production',
      solarSub: 'your panels per year',
      directSelfUse: 'Direct self-consumption',
      exportedToGrid: 'Exported to grid',
      exportedSub: 'unused surplus',
      gridImport: 'Grid import',
      gridImportSub: 'you pay full tariff',
      feedinCosts: 'Feed-in costs',
      feedinSub: 'fixed fee to your supplier',
      solarEqualSub: 'Same as the current situation',
      baSelfConsumpSubL: 'Share of generated solar energy used directly in the home',
      baSelfConsumpSubR: 'Increased through storage and optimized use of solar energy',
      baSelfDirectSubFull: 'Share of your total consumption covered directly by solar energy',
      baTerugSubL: 'Surplus solar energy is fed back to the electricity grid',
      baTerugSubR: 'Surplus is stored in the battery and used in the home later',
      baNetInjectie: 'Remaining grid injection',
      baNetInjectieSub: (gross, stored, net) => `Of ${gross} kWh surplus: ${stored} kWh stored, ${net} kWh still to grid`,
      baNetDepSubL: 'How much of your energy needs are met by your own generation',
      baNetDepSubR: 'Strongly increased by using stored and locally generated energy',
      baGridImportSubL: 'Buying electricity from the grid when generation is insufficient',
      baGridImportSubR: 'Strongly reduced by deploying stored solar energy',
      baMarktOpt: 'Smart market optimization',
      baMarktSubL: 'Not active in the current situation',
      baMarktSubR: 'Energy is charged at low hourly prices and used or exported at high market prices',
      baBatStorage: 'Self-used instead of exported',
      baBatStorageSub: 'Surplus solar energy is stored and self-used instead of exported to the grid',
      baFeedinSubL: 'Not applicable in the current situation',
      baFeedinSubR: 'Not applicable within a dynamically managed energy system',
      baFeedinActiveSubL: 'What you currently pay in feed-in costs on your exported energy',
      baFeedinActiveSubR: 'Less exported energy through storage → lower feed-in costs',
      totalSelfUse: 'Total self-consumption',
      stillExported: 'Still exported',
      lessToGrid: (n) => `${n} kWh less to grid`,
      gridImportWithSub: (n) => `${n} kWh less than now`,
      energySaving: 'Energy savings',
      energySavingSub: (tk) => `less grid import${tk > 0 ? ' + no feed-in costs' : ''}`,
      smartOptTitle: 'Smart market optimisation',
      smartOptDesc: 'Your battery charges when electricity is cheap and supplies at expensive peak hours. You automatically benefit from daily price differences on the energy market.',
      viaEpex: 'via EPEX SPOT connection',
      financialOverview: 'Financial overview',
      investment: 'Investment',
      annualBenefit: 'Annual benefit',
      paybackPeriod: 'Payback period',
      netAfter10Label: 'Net after 10 years',
      inclInstall: (kWh) => `${kWh} kWh incl. installation`,
      year: 'year',
      viewCalc: 'View full calculation',
      gridAvoided: 'Grid import avoided',
      lessExportRevenue: 'Less export revenue',
      missedExportTotal: 'Missed feed-in revenue',
      feedinSaved: 'Feed-in costs saved',
      feedinMissed: 'Feed-in bonus missed',
      emsArbitrage: 'EMS arbitrage (direct)',
      subtotalEnergy: 'Energy subtotal',
      emsDayPeak: 'EMS peak optimisation',
      totalAnnual: 'Total annual benefit',
      calcDisclaimer: 'Steps 1–2 are based on your inputs and live EPEX market data. Step 3 uses the CBS historical average (~5%/yr, 2010–2024). Step 4 follows the statutory phase-out of net-metering 2027–2031. Actual results may vary.',
      emsExplainer: 'Your AlphaESS EMS automatically trades on the energy market. The system charges at low EPEX prices and supplies at peak hours. This is the biggest value driver of your system — fully automatic, day and night.',
      warmtefondsLabel: 'National Heat Fund',
      warmtefondsTitle: 'Financing via VOLTRAX, 0% interest possible',
      warmtefondsDesc: 'Borrow up to \u20ac8,500 via the National Heat Fund. With income below \u20ac60,000 you pay 0% interest. We arrange everything.',
      warmteTags: ['Up to \u20ac8,500', '0% interest possible', 'We arrange everything'],
      ctaTitle: 'Ready for personal advice?',
      ctaDesc: 'Based on this report our specialists will prepare a tailored quote. Completely without obligation.',
      ctaBtn: 'Request free advice',
      disclaimer: 'Indicative calculation based on your consumption data and market averages. Actual results may vary.',
      recalculate: 'Enter different numbers',
      personalReport: 'Personal energy report',
      maximaalVoordeel: 'Maximum benefit',
      perDayLabel: 'Per day',
      howItWorksTitle: 'How your AlphaESS works',
      howStep1Title: 'Battery learns your pattern',
      howStep1Desc: 'During the first 4 weeks the system analyses your consumption and builds up to maximum efficiency.',
      howStep2Title: '35\u201390% for solar power',
      howStep2Desc: "This part of the capacity stores your own solar power and supplies it in the evening when the panels stop.",
      howStep3Title: 'Rest plays the energy market',
      howStep3Desc: 'The remaining buffer automatically charges at low EPEX prices and discharges at peak hours. Day and night, fully automatic.',
      waitingTitle: 'What you are losing without a battery',
      waitingMissedSavings: 'Missed savings',
      waitingExtraCosts: 'Extra grid costs',
      waitingFeedin: 'Feed-in costs',
      waitingTotal: 'Total missed per year',
      waitingPerMonth: (n) => `Every month you wait costs you \u20ac${n} in missed savings.`,
      waitingBanner: (low, high) => `Every month without a battery you are leaving an estimated \u20ac${low}\u2013\u20ac${high} of value on the table.`,
      calcExplainGridAvoided: (kwh, pE) => `You avoided ${kwh} kWh of grid import \u00d7 \u20ac${pE}/kWh. Solar power stored during the day, used in the evening.`,
      calcExplainExportLoss: (kwh, pT) => `${kwh} kWh now stays in your home instead of being exported at \u20ac${pT}/kWh. This is the honest deduction.`,
      calcExplainArbitrage: (kwh, pE, pT) => `${kwh} kWh \u00d7 (\u20ac${pE} \u2212 \u20ac${pT}) \u00d7 22% return margin.`,
      calcExplainEms: (totalCycles, solarCycles, bat, spreadLow, spreadHigh, emsLow, emsHigh) =>
        `Your battery makes ${totalCycles} charge/discharge cycles per year. ${solarCycles} come from solar power, the rest are pure EPEX cycles: charging at \u20ac${spreadLow}/kWh, discharging at \u20ac${spreadHigh}/kWh. ${totalCycles} cycles \u00d7 ${bat} kWh \u00d7 \u20ac${spreadLow}\u2013\u20ac${spreadHigh} = \u20ac${emsLow}\u2013\u20ac${emsHigh}/year.`,
      dynamicContractLabel: 'Do you have a dynamic energy contract?',
      dynamicNo: 'No, fixed tariff',
      dynamicYes: 'Yes, dynamic (EPEX)',
      dynamicHint: 'Your battery benefits fully from hourly price differences on the energy market.',
      perJaarShort: 'per year',
      valueBreakdownTitle: 'How you earn back',
      valueBreakdownBullets: [
        'Use more of your own solar energy',
        'Buy less electricity from the grid',
        'Export less at low feed-in rates',
        'Smart charging and discharging at dynamic prices',
      ],
      v1Lbl: 'Less grid import',
      v1Sub: 'Your own solar power used in the evening and at night, not given away to the grid',
      v2Lbl: 'Feed-in costs avoided',
      v2Sub: 'No more extra feed-in charges from your energy supplier',
      v3Lbl: 'Smart battery control',
      v3Sub: 'Automatically charge at low electricity price, discharge at high price',
      openDetails: 'How is this calculated?',
      step1Basis: 'Less grid electricity to buy',
      step1BasisSub: 'You use your own solar power — every kWh you don\'t buy saves money directly',
      step2Epex: 'Smart charging and discharging',
      step2EpexSub: 'Automatically charges at low EPEX tariffs, discharges at expensive peak hours — day and night, fully automatic',
      step3Uplift: 'Energy gets more expensive every year',
      step3UpliftSub: 'Based on CBS energy price development ~5%/yr · your savings grow automatically',
      step4Bonus: 'Net-metering disappears 2027–2031',
      step4BonusSub: 'You\'ll feed back almost nothing — your battery catches that',
      infoNotBaseline: 'Informational projection — not in baseline',
      totalBenefitLabel: 'Total estimated annual benefit',
      smartTitle: 'Smart optimisation with AlphaESS',
      smartSubTrigger: 'Click for explanation: how does the battery charge and discharge smartly?',
      smartP1: 'Your AlphaESS battery continuously monitors the current electricity price. The system independently decides when charging is profitable and when you can feed back or use energy internally.',
      smartBullet1: 'Automatically charges at low or negative EPEX prices',
      smartBullet2: 'Discharges at expensive peak hours, you pay nothing to the grid then',
      smartBullet3: 'Fully automatic, day and night, no action required',
      smartRangeLbl: 'Extra value via smart control',
      netResultTitle: 'Net result after 10 years',
      netResultSub: (price) => `After recovering your investment of \u20ac${price}, this is what remains`,
      baTitle: 'Your situation: before and after the battery',
      baCurrentTag: 'Current',
      baNewTag: 'With battery',
      baWithTitle: 'With AlphaESS battery',
      baSelfConsump: 'Self-consumption',
      baSelfConsumpSub: 'of own solar power used',
      baSelfConsumpBasis: '% of your solar production',
      baGridImport: 'Grid import',
      baExport: 'Self-used from solar',
      baExportSubBefore: 'direct from your solar panels',
      baExportSubAfter: 'via solar panels + battery',
      baNetCosts: 'Annual grid costs',
      baNetCostsSub: 'incl. feed-in costs',
      baNetEarning: 'Net grid earnings',
      baNetEarningSub: 'your export revenue exceeds your grid import cost',
      baAnnualSaving: 'Annual savings',
      baCurrentDynamic: 'Current dynamic contract',
      baCurrentFixed: 'Current fixed contract',
      baCurrentDynamicHint: 'With battery you switch to dynamic \u2014 maximum return',
      baNewDynamic: 'Dynamically optimised + battery',
      baNewFixed: 'Dynamic contract + battery',
      baSolarOutput: 'Total solar production',
      baSolarOutputSub: 'Your annual generation via solar panels',
      baSelfDirect: 'Direct self-use',
      baSelfDirectSub: 'of your consumption covered by solar',
      baTeruglevering: 'Grid export',
      baTerugleveringSub: (pT, pE) => `you receive \u20ac\u2009${pT}/kWh \u2014 but buy back at \u20ac\u2009${pE}/kWh`,
      baNetDep: 'Self-sufficiency',
      baNetDepSub: '% of your consumption from own sources',
      baMissedValue: 'Electricity value lost',
      baMissedValueSub: 'energy you sell cheaply but buy back at full price',
      baBatCaptures: 'Battery captures',
      baBatCapturesSub: 'solar surplus used instead of exported',
      baSelfUsedNotExported: (n) => `${n} kWh self-used instead of exported`,
      baGridImportBatterySub: (n) => `${n} kWh less imported thanks to battery use`,
      baEpexRow: 'EPEX dynamic contract',
      baEpexRowSub: 'auto-charge at low hourly rates, discharge at peaks',
    },
  },
}

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('nl')
  return (
    <LanguageContext.Provider value={{ lang, setLang, t: T[lang] }}>
      {children}
    </LanguageContext.Provider>
  )
}
